image: node-yarn

before_script:
  - yarn install

cache:
  paths:
    - node_modules/

pages:
  script:
    - yarn generate:modern
    - mv dist public
  artifacts:
    paths:
      - public
  only:
    - master
